### ISSUE TITLE
进入教室后无法弹出课堂的viewcontroller

### ISSUE THREAD

**Issue by york552** [AgoraIO-Community/CloudClass-iOS#21]
仿照该示例开发一个直播网课app，在进入教室后无法弹出课堂的视图，网络请求没有问题，怀疑是结构问题。与示例不同，我的app外面还有一个UItabBarController，不知道是否影响，控制台报warning：
Attempt to present <SmallViewController: 0x1128be800> on <ViewController: 0x111f0b320> whose view is not in the window hierarchy!
请问如何解决呢

**Comment by srs888001** [comment]
你好， 你这边能提供一个简单demo吗？ 我们这边快速验证下问题。

**Comment by york552** [comment]
git@github.com:york552/WebClassMaster-Student.git
麻烦了

**Comment by york552** [comment]
https://github.com/york552/WebClassMaster-Student.git
麻烦了

**Comment by srs888001** [comment]
问题已经找到， 我们需要发布下Pods更新。  应该最迟明天可以发布好， 发布成功我会在这边commit更新。

**Comment by york552** [comment]
好的，谢谢您了

**Comment by srs888001** [comment]
你可以使用最新的AgoraEduSDK再测试下， pod 'AgoraEduSDK', '1.0.1'

**Comment by york552** [comment]
你好 我的pod没有找到1.0.1版本，麻烦看一下是什么原因呢。
![Uploading 截屏2021-04-25 上午11.51.40.png…]()

**Comment by plutoless** [comment]
@york552 试试更新下pod?

**Comment by srs888001** [comment]
![image](https://user-images.githubusercontent.com/5343094/115983825-3672a700-a5d6-11eb-93fe-2d89ef18f91e.png)

试下：
pod install --repo-update

**Comment by york552** [comment]
中午已经弄好啦 谢谢啦

**Comment by york552** [comment]
顺便问一下，灵动课堂会出ios平台的教师版吗

**Comment by srs888001** [comment]
目前暂时没有规划
