### ISSUE TITLE
请问灵动课堂能自定义UI吗

### ISSUE THREAD

**Issue by EdwinXiang** [AgoraIO-Community/CloudClass-iOS#22]
感觉这个灵动集成度很高，没有自定义UI方法呢，能提供demo吗

**Comment by plutoless** [comment]
月底发布的1.1.0版本会正式支持自订UI哈，现在也可以，只是没那么方便

**Comment by EdwinXiang** [comment]
现在自定义的api 有哪些呢，能贴出来让我看下么，我就是没找到可以自定义的api，直接launch就弹出一个高度集成的灵动课堂了

**Comment by plutoless** [comment]
@EdwinXiang 现在源码都是开放的，如果您想看看1.0.0，iOS的源码在这个分支
https://github.com/AgoraIO-Community/CloudClass-iOS/tree/release/apaas%2F1.0.0
1.0.0没有对接用的api，自订通过项目直接修改源代码就行。1.1.0会有供UI链接的业务API

**Comment by EdwinXiang** [comment]
好的。我这边把你说的分支down下来了，但是看到还是使用的AgoraEduSDK，并没有UI绘制的代码，是不是分支贴错了呢？

**Comment by srs888001** [comment]
不好意思， 麻烦使用分支：https://github.com/AgoraIO-Community/CloudClass-iOS/tree/release/apaas%2F1.1.0
